version: '3'
name: dev_sdlt
services:
    dev_web:
        container_name: dev_sdlt_web
        image: nginx:alpine
        volumes:
            - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./:/var/www/html"
            - "../sdlt-theme:/var/www/html/themes/sdlt"            
            - "../sdlt-framework:/var/www/html/vendor/nzta/sdlt-framework" 
        ports:
            - "666:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - dev_php
        networks:
            - dev_frontend
            - dev_backend
    dev_php:
        container_name: dev_sdlt_php
        image: php:${PHP_VERSION}-fpm
        restart: always
        volumes:
            - "./:/var/www/html"
            - "./docker/setup_php.sh:/opt/setup.sh"
            - "../sdlt-framework:/opt/sdlt-framework"
            - "../sdlt-theme:/opt/sdlt-theme"
            - ./logs/:/var/log
        networks:
            - dev_backend
        command: /bin/sh -c /opt/setup.sh    
networks:
  dev_frontend:
  dev_backend:
volumes:
    data:
